name: dynamic-matrix

on: [push, pull_request]

jobs:
  matrix-setup:
    runs-on: ubuntu-latest
    env:
      PM_URL: https://pm.community.intersystems.com/packages/-/all?allVersions=1
      JQ_SCRIPT: reduce .[] as $item ([]; if $item.allVersions | length >= 65 then . + [$item.name] else . end)
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          matrix=$(curl -L "$PM_URL" | jq -cr "$JQ_SCRIPT")
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  run-builds:
    runs-on: ubuntu-latest
    needs: matrix-setup
    strategy:
      matrix:
        package: ${{ fromJson(needs.matrix-setup.outputs.matrix) }}
    steps:
      - name: print
        run: echo "MATRIX ${{ matrix.package }} "
